apiVersion: batch/v1
kind: CronJob
metadata:
  name: hnjobs-parser-often
spec:
  schedule: "*/49 * 1-5 * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: 900
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: hnjobs-parser-often
              image: ghcr.io/hnjobs/parser:SHORT_SHA
              env:
                - name: ELASTICSEARCH_HOST
                  value: "192.168.0.4"
                - name: ELASTICSEARCH_PORT
                  value: "7940"
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hnjobs-parser-rarely
spec:
  schedule: "49 */4 6-31 * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: 900
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: hnjobs-parser-rarely
              image: ghcr.io/hnjobs/parser:SHORT_SHA
              env:
                - name: ELASTICSEARCH_HOST
                  value: "192.168.0.4"
                - name: ELASTICSEARCH_PORT
                  value: "7940"
          restartPolicy: Never
